# Generated by Django 6.0.2 on 2026-02-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('DELIVERED', 'delivered')], default='PENDING', max_length=255),
        ),
    ]
